### ISSUE TITLE
Timer Heart Ban

### ISSUE THREAD

**Issue by SkeloD** [KartoffelChipss/LifeStealZ#51]
**Is your feature request related to a problem? Please describe.**
Its not related to any problem

**Describe the solution you'd like**
Its like a normal heart ban but after like 5 weeks or so they will be unheart ban, let us chose the time in the config

**Describe alternatives you've considered**
I don't have any other alternative solution

**Additional context**
N.T.A ( Nothing to add )

**Comment by abb3v** [comment]
@SkeloD You can already achieve something similar to this using a disablePlayerBanOnElimination. In the config, enable the aforementioned setting, and in the list add a tempban provided by an external plugin that will manage this:
```yaml
disablePlayerBanOnElimination: true // ensure this is true (defaulted to false)

eliminationCommands:
- tempban &player& <insert some reason here> 1d
```

--- 
*If this was not able to help your issue, please let us know further :)*
